services:
  postgres:
    image: postgres:16-alpine
    container_name: turnos-users-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: turnos
      POSTGRES_PASSWORD: turnos123
      POSTGRES_DB: turnos_users
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
